<div class="container">
    <h3> Publisher Dashboard</h3>
    <a class="btn btn-primary pull-right" href="<?php echo SITE_URL .'/publisher/zone/add'?>">New zone</a>
    <hr>

    <?php if (empty($this->zoneData)) { ?>
        <h3>No zone found!</h3>
        <?php return;} else { ?>
    <table class="table table-bordered text-right">
        <thead>
        <tr>
            <th>ZoneId</th>
            <th>Name</th>
            <th>CreateTime</th>
            <th>Format</th>
            <th>Width</th>
            <th>Height</th>
            <th>Embed Code</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->zoneData as $key => $zone) { ?>
            <tr>
                <td> <?php echo $zone["ZoneId"]; ?> </td>
                <td> <?php echo $zone["ZoneName"]; ?> </td>
                <td> <?php $date=date_create($zone["ZoneCreateTimestamp"]); echo date_format($date, 'd/m/Y H:i:s'); ?> </td>
                <td> <?php echo $zone["ZoneFormat"] == '202' ? 'Html5 Video' : 'Image Ad'; ?> </td>
                <td> <?php echo $zone["ZoneWidth"]; ?> </td>
                <td> <?php echo $zone["ZoneHeight"]; ?> </td>
                <td> <a href="" data-zone-id="<?php echo $zone["ZoneId"]; ?>" data-zone-width="<?php echo $zone["ZoneWidth"]; ?>" data-zone-height="<?php echo $zone["ZoneHeight"]; ?>" data-toggle="modal" data-target="#getcodeModal" class="btn btn-default btn-get-embed-code">Get code</a> </td>
                <td> <?php echo ($zone["ZoneStatus"] == "1" ? '<span class="label label-warning"> Pending</span>' : ($zone["ZoneStatus"] == "2" ? '<span class="label label-success"> Approved</span>' : '<span class="label label-default"> Inactive</span>')); ?></td>
                <td>
                    <a title="Edit Zone" href="<?php echo SITE_URL .'/publisher/zone/edit/?id=' . $zone["ZoneId"] . '&name=' . $zone["ZoneName"] . '&width=' . $zone["ZoneWidth"] . '&height=' . $zone["ZoneHeight"] . '&format=' . $zone["ZoneFormat"] ?>"><i class="fa fa-pencil"></i></a>
                    <?php
                    $linkUpdateStatus = SITE_URL .'/publisher/zone/updatestatus?id=' . $zone["ZoneId"];
                    ?>
                    <?php if ($zone["ZoneStatus"] != 0) {?>
                        <a title="Deactivate Zone" href="<?php echo $linkUpdateStatus . '&status=0';?>"><i class="icon-cancel"></i></a>
                    <?php } elseif ($zone["ZoneStatus"] != 1) {?>
                        <a title="Activate Zone" href="<?php echo $linkUpdateStatus . '&status=1';?>"><i class="fa fa-check-square-o"></i></a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php } ?>
</div>
<!-- Modal -->
<div id="getcodeModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Copy scripts onto website to play ads</h4>
            </div>
            <div class="modal-body">
                To <code> &lt;head&gt; </code> tag, only need one:
                <br>
                <code>
                    &lt;script src="http://localhost/spl_adnetwork/static/js/embed/js/adsbyphamtrongphat.js" async=""&gt;&lt;/script&gt;
                </code>
                <br>
                And to where put ads:
                <br>
                <code id="embedZone">
                    &lt;ins class="adsbypspl" data-zone="" data-ad-width="" data-ad-height=""&gt;&lt;/ins&gt;<br>
                    &lt;script&gt; (adsbypspl = window.adsbypspl || []).push({}); &lt;/script&gt;
                </code>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
