<div class="panel panel-default col-lg-10">

    <div class="panel-heading">
        <h3 class="panel-title"><i class="icon-credit-card"></i>&nbsp;Quick Topup Balance <?php if (isset($this->activeBalance)) { echo ', currently having <b class="bold_red" id="lbl_navbar_balance">' . $this->activeBalance["UserBalance"] . '</b> VND in account'; }?></h3>
    </div>

    <div class="panel-body">
        <form action="" method="POST" class="form-horizontal form-recharge" novalidate="novalidate">
            <div class="form-group">
                <label for="" class="control-label col-sm-2">Master card info.</label>

                <div class="col-sm-4">
                    <input type="text" name="input_price" maxlength="100" id="cardNumber" class="form-control">
                </div>
                <div class="col-sm-2">
                    <input type="text" name="input_price" maxlength="100" id="cardPin" class="form-control">
                </div>
                <div class="col-sm-2">
                    <input type="text" name="input_price" maxlength="100" id="cardPin1" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="control-label col-sm-2">Amount: </label>

                <div class="col-sm-6">
                    <input type="number" name="amount" maxlength="100" id="amount" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-8 col-sm-offset-2">
                    <span class="text-muted">Enter top up, mininum 50,000 VNĐ</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary">Topup</button>
                </div>
            </div>
        </form>
    </div>
</div>