<div class="container panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title"><i class="icon-credit-card"></i>&nbsp<?php if (isset($this->activeBalance)) { echo 'You currently having <b class="bold_red" id="lbl_navbar_balance"><span class="timer" data-from="0" data-to="' . $this->activeBalance["UserBalance"] . '"></span></b> VND in account'; }?></h3>
    </div>

</div>