<div class="col-md-6 span10" style="float: right;min-height: 636px;">
    <div class="row-fluid">
        <div class="box span12">
            <div class="box-content">
                <div class="row-fluid">
                    <div class="span4 statbox purple" style="cursor: pointer;margin-bottom: 0;">
                        <div style="font-size: 18px;">Click</div>
                        <div class="number" style="right: 30%;top: 40%;"><span class="timer" data-from="0" data-to="<?php echo $this->clicks; ?>"></span> <i class="fa fa-edit"></i></div>
                    </div>
                    <div class="span4 statbox green" style="cursor: pointer;margin-bottom: 0;">
                        <div style="font-size: 18px;">Impression</div>
                        <div class="number" style="right: 30%;top: 40%;"><span class="timer" data-from="0" data-to="<?php echo $this->impressions; ?>"></span> <i class="fa fa-check-square-o"></i></div>
                    </div>
                    <div class="span4 statbox yellow" style="cursor: pointer;margin-bottom: 0;">
                        <div style="font-size: 18px;">Trueview</div>
                        <div class="number" style="right: 30%;top: 40%;"> <span class="timer" data-from="0" data-to="<?php echo $this->trueviews; ?>"></span> <i class="fa fa-arrow-up"></i></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>