<div class="Wrapcontainer">
    <div class="wrap-success">
        <div class="container container_forgot">
            <div class="form">
                <div class="form_log">
                    <div class="content_form">
                        <form action="<?php echo SITE_URL .'/user/forgotpass'?>" id="form_forgotpass" autocomplete="off" method="POST" role="form" novalidate="novalidate">
                            <div class="inner_form">
                                <p class="tit_form">Create new password</p>
                                <ul class="input_box">
                                    <li><label class="ico_email"></label>
                                        <input type="text" class="input_contact" id="email" name="email" placeholder="Email">
                                    </li>
                                </ul>
                                <ul class="input_box">
                                    <li><label class="ico_email"></label>
                                        <input type="text" class="input_contact" id="name" name="name" placeholder="Registered Name">
                                    </li>
                                </ul>
                                <ul class="input_box">
                                    <li><label class="ico_email"></label>
                                        <input type="password" class="input_contact" id="newpass" name="newpass" placeholder="New password">
                                    </li>
                                </ul>
                                <ul class="input_box">
                                    <li><label class="ico_email"></label>
                                        <input type="password" class="input_contact" id="confirmPassword" name="confirmPassword" placeholder="Confirm password">
                                    </li>
                                </ul>
                                <button type="submit" id="submit" class="form_btn btn btn-primary">Confirm</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
