<div class="popup_login" id="login_block" style="display: block">
    <a title="Close" href="<?php echo SITE_URL . '/user/index'?>"><span class="close_pop"></span></a>
    <form action="<?php echo SITE_URL . '/user/verify'?>" method="POST" id="form_login" autocomplete="off" novalidate="novalidate" class="form-signin">
        <div class="form_log_pop">
            <div class="inner_form_pop">
                <p class="tit_form_bold">Please sign in</p>
                <ul>
                    <li>
                        <label class="sr-only" for="inputEmail">Email address</label>
                        <input type="email" autofocus="" required="" placeholder="Email address" class="form-control" name="email" id="email">
                    </li>
                    <li>
                        <label class="sr-only" for="inputPassword">Password</label>
                        <input type="password" required="" placeholder="Password" class="form-control" name="password" id="password">
                    </li>
                </ul>
                <p class="forget_pass_pop">Forgot password?
                    <a href="<?php echo SITE_URL . '/user/forgotpass'?>">Change password</a></p>

                <button type="submit" class="form_btn_pop dn_btn_pop">Sign in</button>
            </div>
        </div>
    </form>
    <div class="form_log_pop res_box">
        <div class="inner_form_pop">
            <p class="tit_form_pop">Don't have an account?</p>

            <p class="tit_form_bold">Sign up now!</p>

            <p>Join the Ad Network Community for benefits:</p>
            <ul class="list_services">
                <li>As an Advertiser or a Publisher</li>
                <li>Experience top world-class features</li>
            </ul>
            <a href="<?php echo SITE_URL . '/user/register'?>" class="form_btn_pop dk_btn_pop" id="popup_dangky">Register</a>
        </div>
    </div>
</div>
