<div class="container">
    <form action="<?php echo SITE_URL . '/user/verify'?>" method="POST" id="form_login" autocomplete="off" novalidate="novalidate" class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label class="sr-only" for="inputEmail">Email address</label>
        <input type="email" autofocus="" required="" placeholder="Email address" class="form-control" name="email" id="email">
        <label class="sr-only" for="inputPassword">Password</label>
        <input type="password" required="" placeholder="Password" class="form-control" name="password" id="password">
<!--        <div class="checkbox">-->
<!--            <label>-->
<!--                <input type="checkbox" name="autologin" id="autologin"><label for="autologin">Remember me</label>-->
<!--            </label>-->
<!--        </div>-->
        <p class="forget_pass_pop">Forgot password?
            <a href="<?php echo SITE_URL . '/user/forgotpass'?>">Change password</a></p>
        <p class="forget_pass_pop">Don't have account?
            <a href="<?php echo SITE_URL . '/user/register'?>" class="form_btn_pop dk_btn_pop" id="popup_dangky">Register account</a></p>

<!--        <p class="forget_pass_pop">Login as</p>-->
<!--        <ul class="radio_checkbox_pop">-->
<!--            <li>-->
<!--                <input type="radio" name="choice" id="choice1" value="1" checked="checked"><label for="choice1">Nhà quảng cáo</label>-->
<!--            </li>-->
<!--            <li>-->
<!--                <input type="radio" name="choice" id="choice2" value="2"><label for="choice2">Publisher</label>-->
<!--            </li>-->
<!--        </ul>-->
        <button type="submit" class="btn btn-lg btn-primary btn-block" style="height: 36px;">Sign in</button>
    </form>
</div>
