<!--<div class="opacity_bg" style="display: block;"></div>-->

<div class="popup_login" id="res_block" style="display: block;">
    <a title="Close" href="<?php echo SITE_URL . '/user/index'?>"><span class="close_pop"></span></a>
    <div class="form_log_pop">
        <div class="inner_form_pop">
            <form action="" method="POST" role="form" autocomplete="off" id="form-register">
                <legend>
                    Register
                </legend>
                <br>
                <div class="form-group">
                    <div class="input-group">
                        <input value="" type="text" class="form-control" id="fullname" name="fullname" placeholder="Fullname">
                        <span class="input-group-addon"><i class="icon-user"></i></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="validate-content-insert-after">
                        <div class="input-group">
                            <input type="text" class="form-control" id="email" name="email" placeholder="Email">
                            <span class="input-group-addon"><i class="icon-mail-alt"></i></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input value="" type="text" class="form-control" id="phone" name="phone" placeholder="Phonenumber">
                        <span class="input-group-addon"><i class="icon-user"></i></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="password" class="form-control" id="password" name="password" placeholder="Mật khẩu">
                        <span class="input-group-addon"><i class="icon-key"></i></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="password" class="form-control" id="replypassword" name="replypassword"
                               placeholder="Nhập lại mật khẩu">
                        <span class="input-group-addon"><i class="icon-key"></i></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="radio" name="userRole" value="2" checked>Publisher
                        <input type="radio" name="userRole" value="3">Advertiser
                    </div>
                </div>
                <hr>
                <button type="submit" id="submit" class="btn btn-primary btnDangky">Sign Up</button>
            </form>
        </div>
    </div>
</div>
