<div class="container">
    <div class="col-md-5">
        <form action="" method="POST" id="form_add_banner" autocomplete="off" novalidate="novalidate" class="form-signin">
            <h2 class="form-signin-heading">Add new zone</h2>

            <label class="sr-only" for="inputTitle">Name</label>
            <input type="text" autofocus="" required="" placeholder="Name" class="form-control" name="name" id="name">

            <label>Placement:</label>
            <input type="radio" name="placement" id="placement1" value="300x250" checked="checked"><label for="placement1">300x250</label>
            <input type="radio" name="placement" id="placement2" value="300x600"><label for="placement2">300x600</label>
            <input type="radio" name="placement" id="placement3" value="480x270"><label for="placement3">480x270</label>
            <br>
            <label for="format">Format:</label>
            <input type="radio" name="format" id="101" value="101" checked="checked"><label for="101">Image Ad</label>
            <input type="radio" name="format" id="202" value="202"><label for="202">Rich Media Video</label>
            <div class="bold_red" id="hint"></div>
            <br>
            <br>
            <button type="submit" class="btn btn-lg btn-primary btn-block" style="height: 36px;width:20%;float:left;">Add</button>
            <button type="button" class="btn btn-default" onclick="history.back();" style="height: 36px;width:20%;float:left;">Cancel</button>
        </form>
    </div>
</div>

