<div class="container">
    <div class="col-md-5">
        <form action="" method="POST" id="form_add_banner" autocomplete="off" novalidate="novalidate" class="form-signin">
            <h2 class="form-signin-heading">Add new zone</h2>

            <label>Zone Title</label>
            <input type="text" autofocus="" required="" placeholder="Name" class="form-control" name="name" id="name">
            <br>
            <label>Placement:</label>
            <select class="form-control" name="placement" id="placement">
                <option value="300x250">300x250</option>
                <option value="300x600">300x600</option>
                <option value="480x270">480x270</option>
            </select>
            <br>
            <label for="format">Format:</label>
            <select class="form-control" name="format" id="format">
                <option value="101">Image Ad</option>
                <option value="202">Rich Media Video</option>
            </select>
            <div class="bold_red" id="hint"></div>
            <br>
            <br>
            <button type="submit" class="btn btn-lg btn-primary btn-block" style="height: 36px;width:20%;float:left;">Add</button>
            <button type="button" class="btn btn-default" onclick="history.back();" style="height: 36px;width:20%;float:left;">Cancel</button>
        </form>
    </div>
</div>

