<div class="container">
    <div class="col-md-5">
        <form action="<?php echo SITE_URL . '/publisher/zone/edit'?>" method="POST" id="form_add_banner" autocomplete="off" novalidate="novalidate" class="form-signin">
            <h2 class="form-signin-heading">Edit Zone <?php echo $this->editZone['id'];?></h2>
            <input type="hidden" value="<?php echo $this->editZone['id'];?>" name="id" id="id">

            <div class="">
                <label class="sr-only" for="inputTitle">Name</label>
                <input type="text" value="<?php echo $this->editZone['name'];?>" autofocus="" required="" placeholder="Name" class="form-control" name="name" id="name">

            </div>
            <div class="">

                <label class="sr-only" for="inputFormat">Format</label>
                <input type="text" value="<?php echo $this->editZone['format'];?>" required="" placeholder="Format" class="form-control" name="format" id="format">

            </div>

            <div class="">
                <label>Placement:</label>
                <?php $placement = join("x", array($this->editZone['width'], $this->editZone['height']))?>
                <input type="radio" name="placement" id="placement1" value="300x250" <?php echo (($placement == "300x250") ? 'checked="checked"' : '')?>><label for="placement1">300x250</label>
                <input type="radio" name="placement" id="placement2" value="300x600" <?php echo (($placement == "300x600") ? 'checked="checked"' : '')?>><label for="placement2">300x600</label>
                <input type="radio" name="placement" id="placement3" value="480x270" <?php echo (($placement == "480x270") ? 'checked="checked"' : '')?>><label for="placement3">480x270</label>
            </div>
            <br>
            <br>
            <button type="submit" class="btn btn-lg btn-primary btn-block" style="height: 36px;width:20%;float:left;">Edit</button>
            <button type="button" class="btn btn-default" onclick="history.back();" style="height: 36px;width:20%;float:left;">Cancel</button>
        </form>
    </div>
</div>

