<div class="wrap-footer" style="text-align: center;">
    <div class="container container_footer">
        <p class="social">
            <a href="https://www.facebook.com/eClickAds" target="_blank"><img src="https://stiad.eclick.vn/v46/images/default/fb.png" alt="" title=""></a>
            <a href="https://twitter.com/eClickAds" target="_blank"><img src="https://stiad.eclick.vn/v46/images/default/twit.png" alt="" title=""></a>
            <a href="https://plus.google.com/u/2/b/111937888998223119809/dashboard/overview" target="_blank"><img src="https://stiad.eclick.vn/v46/images/default/g+.png" alt="" title=""></a>
        </p>
        <p>Copyright © 2015 eClick. All rights reserved.</p>
    </div>
</div>
