<div class="col-md-3 left_col">
    <div class="left_col scroll-view" tabindex="5000" style="overflow: hidden; outline: none; cursor: -webkit-grab;">

        <div class="navbar nav_title" style="border: 0;z-index: 9">
            <a href="<?php echo SITE_URL .'/admin/index'?>" class="site_title"><i class="fa fa-paw"></i> <span> Admin Dashboard Logo </span></a>
        </div>
        <div class="clearfix"></div>

        <br>
            <div class="sidebar">
                <div class="mini-submenu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </div>
                <div class="list-group">
        <span class="list-group-item active">
            Control
            <span class="pull-right" id="slide-submenu">
                <i class="fa fa-times"></i>
            </span>
        </span>

        <a id="anchorIndex" href="<?php echo SITE_URL .'/admin/index'?>" class="list-group-item">
            <i class="fa fa-history"></i> Index
        </a>
        <a href="<?php echo SITE_URL .'/admin/banner'?>" class="list-group-item">
            <i class="fa fa-folder-open-o"></i> Banner <span class="badge"><?php echo $this->layout()->pendingBanners; ?></span>
        </a>
        <a href="<?php echo SITE_URL .'/admin/zone'?>" class="list-group-item">
            <i class="fa fa-folder-open-o"></i> Zone <span class="badge"><?php echo $this->layout()->pendingZones; ?></span>
        </a>
        <a href="<?php echo SITE_URL .'/admin/user'?>" class="list-group-item">
            <i class="fa fa-user"></i> User
        </a>
                </div>
                </div>
    </div>
</div>