<div class="col-md-3 left_col">
    <div class="left_col scroll-view" tabindex="5000" style="overflow: hidden; outline: none; cursor: -webkit-grab;">

        <div class="navbar nav_title" style="border: 0;z-index: 9">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span> Admin Dashboard Logo </span></a>
        </div>
        <div class="clearfix"></div>


        <br>
            <div class="sidebar">
                <div class="mini-submenu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </div>
                <div class="list-group">
        <span class="list-group-item active">
            Control
            <span class="pull-right" id="slide-submenu">
                <i class="fa fa-times"></i>
            </span>
        </span>
                    <a href="<?php echo SITE_URL .'/admin/advertiser'?>" class="list-group-item">
                        <i class="fa fa-user"></i> Banner <span class="badge">14</span>
                    </a>
                    <a href="<?php echo SITE_URL .'/admin/publisher'?>" class="list-group-item">
                        <i class="fa fa-user"></i> Zone <span class="badge">14</span>
                    </a>
<!--                    <a href="#" class="list-group-item">-->
<!--                        <i class="fa fa-user"></i> Advertiser Analytic-->
<!--                    </a>-->
<!--                    <a href="#" class="list-group-item">-->
<!--                        <i class="fa fa-folder-open-o"></i> Publisher Analytic-->
<!--                    </a>-->
                    <a href="<?php echo SITE_URL .'/admin/user'?>" class="list-group-item">
                        <i class="fa fa-user"></i> User
                    </a>
<!--                    <a href="#" class="list-group-item">-->
<!--                        <i class="fa fa-envelope"></i> Lorem ipsum-->
<!--                    </a>-->
                </div>
                </div>
    </div>
</div>