<div id="navbar" class="navbar navbar-default" style="height: 50px;margin-bottom: 10px;">
    <ul class="nav navbar-nav navbar-right">
        <!--        <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>-->
        <!--        <li><a href="../navbar-static-top/">Static top</a></li>-->


        <li class="user" style="vertical-align: middle;">
            <a href="#">
                <span>Hi,  <strong><?php echo $this->layout()->fullname; ?></strong></span>
            </a>
        </li>

        <li style="margin-right: 10px;"><a href="<?php echo SITE_URL .'/user/forgotpass'?>">Change Password</a></li>
        <li style="margin-right: 10px;"><a href="<?php echo SITE_URL .'/' . ($this->layout()->role == 1 ? 'auth' : 'user') .'/logout'?>">Log out</a></li>
    </ul>
</div><!--/.nav-collapse -->