<div class="container">
    <h3> Advertiser Dashboard</h3>
    <a class="btn btn-primary pull-right" href="<?php echo SITE_URL .'/advertiser/banner/add'?>">New Banner</a>
    <hr>

    <?php if (empty($this->bannerData)) { ?>
        <h3>No banner found!</h3>
        <?php return;} ?>
    <table class="table table-bordered text-right">
        <thead>
        <tr>
            <th>BannerId</th>
            <th>Creative</th>
            <th>Format</th>
            <th>Placement</th>
            <th>Method</th>
            <th>Price</th>
            <th>Info</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->bannerData as $key => $banner) { ?>
            <tr>
                <td> <?php echo $banner["BannerId"]; ?> </td>
                <td> <?php $bInfo = json_decode($banner["BannerInfo"]); ?>
                    <div class="widget-creative-eclick" style="width:125px;">
                        <img class="widget-thumbnail" src="<?php echo $bInfo->file; ?>">
                    </div>
                </td>
                <td> <?php echo $banner["BannerFormat"] == '202' ? 'Html5 Video' : 'Image'; ?> </td>
                <td> <?php echo $banner["BannerWidth"] . 'x' . $banner["BannerHeight"]; ?> </td>
                <td> <?php echo $banner["BannerMethod"] == '2' ? 'CPM' : 'CPC'; ?> </td>
                <td> <?php echo $banner["BannerPrice"]; ?> VND</td>
                <td class="text-left">
                    Title: <div class="txt_bold"> <?php echo $bInfo->title; ?></div>
                    Url: <div class="txt_email"> <?php echo $bInfo->url; ?></div>
                    <?php if ($banner["BannerFormat"] == 202){ ?>
                        Media File: <div class="txt_email"> <?php echo $bInfo->mediaFile; ?></div>
                    <?php } ?>
                </td>
                <td> <?php echo ($banner["BannerStatus"] == "1" ? '<span class="label label-warning"> Pending</span>' : ($banner["BannerStatus"] == "2" ? '<span class="label label-success"> Approved</span>' : '<span class="label label-default"> Inactive</span>')); ?></td>
                <td>
                    <a title="Edit Banner" href="<?php echo SITE_URL .'/advertiser/banner/edit/?id=' . $banner["BannerId"] . '&price=' . $banner["BannerPrice"] . '&format=' . $banner["BannerFormat"] . '&width=' . $banner["BannerWidth"] . '&height=' . $banner["BannerHeight"] . '&method=' . $banner["BannerMethod"] . '&title=' .  $bInfo->title . '&file=' .  $bInfo->file . '&url=' .  urlencode($bInfo->url) . ($banner["BannerFormat"] == 202 ? '&mediafile=' . urlencode($bInfo->mediaFile) : '')?>"><i class="fa fa-pencil"></i></a>
                    <?php
                    $linkUpdateStatus = SITE_URL .'/advertiser/banner/updatestatus?id=' . $banner["BannerId"];
                    ?>
                    <?php if ($banner["BannerStatus"] != 0) {?>
                        <a title="Deactivate Banner" href="<?php echo $linkUpdateStatus . '&status=0';?>"><i class="icon-cancel"></i></a>
                    <?php } elseif ($banner["BannerStatus"] != 1) {?>
                        <a title="Activate Banner" href="<?php echo $linkUpdateStatus . '&status=1';?>"><i class="fa fa-check-square-o"></i></a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
