<div class="container">
    <h3> Advertiser Dashboard</h3>
    <a class="btn btn-primary pull-right" href="<?php echo SITE_URL .'/advertiser/banner/add'?>">New Banner</a>
    <hr>

    <?php if (empty($this->bannerData)) { ?>
        <h3>No banner found!</h3>
        <?php return;} ?>
    <table class="table table-bordered text-right">
        <thead>
        <tr>
            <th>BannerId</th>
            <th>BannerPrice</th>
            <th>BannerFormat</th>
            <th>BannerWidth</th>
            <th>BannerHeight</th>
            <th>BannerMethod</th>
            <th>BannerInfo</th>
            <th>BannerStatus</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->bannerData as $key => $banner) { ?>
            <tr>
                <td> <?php echo $banner["BannerId"]; ?> </td>
                <td> <?php echo $banner["BannerPrice"]; ?> </td>
                <td> <?php echo $banner["BannerFormat"]; ?> </td>
                <td> <?php echo $banner["BannerWidth"]; ?> </td>
                <td> <?php echo $banner["BannerHeight"]; ?> </td>
                <td> <?php echo $banner["BannerMethod"]; ?> </td>
                <td> <?php
                    $bInfo = json_decode($banner["BannerInfo"]); ?>
                        <div class="txt_bold"> <?php echo $bInfo->title; ?></div>
                        <div class="txt_email"> <?php echo $bInfo->file; ?></div>
                        <div class="txt_email"> <?php echo $bInfo->url; ?></div>
                </td>
                <td> <?php echo ($banner["BannerStatus"] == "1" ? '<span class="label label-warning"> Pending</span>' : ($banner["BannerStatus"] == "2" ? '<span class="label label-success"> Approved</span>' : '<span class="label label-default"> Inactive</span>')); ?></td>
                <td><a href="<?php echo SITE_URL .'/advertiser/banner/edit/?id=' . $banner["BannerId"] . '&price=' . $banner["BannerPrice"] . '&format=' . $banner["BannerPrice"] . '&width=' . $banner["BannerWidth"] . '&height=' . $banner["BannerHeight"] . '&method=' . $banner["BannerMethod"] . '&title=' .  $bInfo->title . '&file=' .  $bInfo->file . '&url=' .  urlencode($bInfo->url)?>">Edit</a></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
