<h1> Advertiser content </h1>
<a class="btn btn-primary pull-right" href="<?php echo SITE_URL .'/advertiser/banner/create'?>">New Banner</a> controler???

<!--<table class="table table-bordered">-->
<!--    <thead>-->
<!--    <tr>-->
<!--        <th>Id</th>-->
<!--        <th>Name</th>-->
<!--        <th>Phone Number</th>-->
<!--        <th>Balance</th>-->
<!--        <th>Role</th>-->
<!--        <th>Status</th>-->
<!--        <th>Action</th>-->
<!--    </tr>-->
<!--    </thead>-->
<!--    <tbody>-->
<!--    --><?php //foreach($this->bannerData as $key => $user) { ?>
<!--        <tr>-->
<!--            <td> --><?php //echo $user["UserId"]; ?><!--</td>-->
<!--            <td>-->
<!--                --><?php //echo $user["UserName"]; ?>
<!--                <div class="txt_email">-->
<!--                    --><?php //echo $user["UserEmail"]; ?>
<!--                </div>-->
<!--            </td>-->
<!--            <td> --><?php //echo $user["UserPhone"]; ?><!-- </td>-->
<!--            <td> --><?php //echo $user["UserBalance"]; ?><!-- </td>-->
<!--            <td>-->
<!--                --><?php //if ($user["UserRole"] == 1) { ?>
<!--                    <span class="label label-default">Admin</span>-->
<!--                --><?php //} elseif ($user["UserRole"] == 2) { ?>
<!--                    <span class="label label-default">Publisher</span>-->
<!--                --><?php //} elseif ($user["UserRole"] == 3) { ?>
<!--                    <span class="label label-default">Advertiser</span>-->
<!--                --><?php //} ?>
<!--            </td>-->
<!--            <td class="text-center">-->
<!--                --><?php //if ($user["UserStatus"] == 1) { ?>
<!--                    <span class="label label-primary">Active</span>-->
<!--                --><?php //} else { ?>
<!--                    <span class="label label-default">Inactive</span>-->
<!--                --><?php //} ?>
<!--            </td>-->
<!--            <td>-->
<!--                <a href="#">SetActive</a>-->
<!--                |-->
<!--                <a href="#">SetAdmin</a>-->
<!--            </td>-->
<!---->
<!--        </tr>-->
<!--    --><?php //} ?>
<!---->
<!--    </tbody>-->
<!--</table>-->