<h1> Advertiser content </h1>
<a class="btn btn-primary pull-right" href="<?php echo SITE_URL .'/advertiser/banner/create'?>">New Banner</a> controler???
<hr>

<?php if (empty($this->bannerData)) { ?>
    <h3>No banner found!</h3>
    <?php return;} ?>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Phone Number</th>
        <th>Balance</th>
        <th>Role</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->bannerData as $key => $banner) { ?>
        <tr>
            <td> <?php echo $banner["UserId"]; ?></td>
            <td>
                <?php echo $banner["UserName"]; ?>
                <div class="txt_email">
                    <?php echo $banner["UserEmail"]; ?>
                </div>
            </td>
            <td> <?php echo $banner["UserPhone"]; ?> </td>
            <td> <?php echo $banner["UserBalance"]; ?> </td>
            <td>
                <?php if ($banner["UserRole"] == 1) { ?>
                    <span class="label label-default">Admin</span>
                <?php } elseif ($banner["UserRole"] == 2) { ?>
                    <span class="label label-default">Publisher</span>
                <?php } elseif ($banner["UserRole"] == 3) { ?>
                    <span class="label label-default">Advertiser</span>
                <?php } ?>
            </td>
            <td class="text-center">
                <?php if ($banner["UserStatus"] == 1) { ?>
                    <span class="label label-primary">Active</span>
                <?php } else { ?>
                    <span class="label label-default">Inactive</span>
                <?php } ?>
            </td>
            <td>
                <a href="#">SetActive</a>
                |
                <a href="#">SetAdmin</a>
            </td>

        </tr>
    <?php } ?>

    </tbody>
</table>