<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/jquery-1.12.2.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/mycustom.js"></script>
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/font-awesome.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/fontello-embedded.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/mycustom.css" rel="stylesheet">
    <?php
    echo $this->headTitle();
    echo $this->headLink();
    ?>
</head>

<body>
<div id="wrapper">
    <?php echo $this->render('/partials/nav_right.phtml'); ?>


    <div id="page-wrapper" class="gray-bg">

        <?php echo $this->render('/partials/nav_header.phtml'); ?>

        <div id="admin_content" class="col-md-9 wrapper wrapper-content">

            <?php echo $this->layout()->content; ?>

        </div>

        <?php echo $this->render('/partials/footer.phtml'); ?>

    </div>

</div>


<script type="text/javascript">
    var SITE_URL = "<?php echo SITE_URL;?>";
    var STATIC_URL = "<?php echo STATIC_URL;?>";
</script>
<?php echo $this->headScript(); ?>

</body>
</html>
