<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/jquery-1.12.2.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/mycustom.js"></script>
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/font-awesome.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/fontello-embedded.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/mycustom.css" rel="stylesheet">
</head>

<body>
<div id="wrapper">
    <div class="col-md-3 left_col">
        <div class="left_col scroll-view" tabindex="5000" style="overflow: hidden; outline: none; cursor: -webkit-grab;">

            <div class="navbar nav_title" style="border: 0;">
                <a href="#" class="site_title"><i class="fa fa-paw"></i> <span> Advertiser Dashboard Logo </span></a>
            </div>
            <div class="clearfix"></div>
            <br>

                <div class="sidebar">
                    <div class="mini-submenu">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </div>
                    <div class="list-group">
                <span class="list-group-item active">
                    Control Panel
                    <span class="pull-right" id="slide-submenu">
                        <i class="fa fa-times"></i>
                    </span>
                </span>
                        <a id="anchorIndex" href="<?php echo SITE_URL .'/advertiser/index'?>" class="list-group-item">
                            <i class="fa fa-history"></i> Index
                        </a>
                        <a href="<?php echo SITE_URL .'/advertiser/banner/analyze'?>" class="list-group-item">
                            <i class="fa fa-comment-o"></i> Analyze
                        </a>
                        <a href="<?php echo SITE_URL .'/advertiser/index'?>" class="list-group-item">
                            <i class="fa fa-search"></i> Banner
                        </a>
                        <a href="<?php echo SITE_URL .'/advertiser/balance/topup'?>" class="list-group-item">
                            <i class="fa fa-user"></i> Balance Info
                        </a>
                    </div>
                </div>

        </div>
    </div>

    <div id="page-wrapper" class="gray-bg">

        <?php echo $this->render('/partials/nav_header.phtml'); ?>

        <div class="wrapper wrapper-content">

            <?php echo $this->layout()->content; ?>

        </div>

<!--        --><?php //echo $this->render('/partials/footer.phtml'); ?>

    </div>

</div>


<script type="text/javascript">
    var SITE_URL = "<?php echo SITE_URL;?>";
    var STATIC_URL = "<?php echo STATIC_URL;?>";
</script>
<?php echo $this->headScript(); ?>

</body>
</html>
