<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/jquery-1.12.2.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/mycustom.js"></script>
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/adsense.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/mycustom.css" rel="stylesheet">
    <?php
    echo $this->headTitle();
    echo $this->headLink();
    ?>
</head>
<body>
<header class="header" role="banner" style="min-height: 0px;">
    <h1 class="product-logo">
        <a href="#"><img alt="Ad network" style="width: 88px;height: 66px" src="<?php echo STATIC_URL; ?>/images/peeredgelogotype.png" srcset="<?php echo STATIC_URL; ?>/images/peeredgelogotype.png 2px">
            <span class="site-name">Ads Solution</span></a>
    </h1>
    <nav class="main-navigation ng-scope" data-ng-controller="rs.navigation.NavCtrl as navCtrl" style="transition: top 0s ease 0s; top: 0px;">
        <h1>
            Ads Solution
        </h1>
        <ul style="padding-right: 93px;">
            <li class="active">Home
            </li>
            <li>
                <a href="#">Benefits</a>
            </li>
            <li>
                <a href="#">How It Works</a>
            </li>
            <li>
                <a href="#">Success Stories</a>
            </li>
            <li>
                <a href="#">Resources</a>
            </li>
            <li>
                <a href="#">Get Started</a>
            </li>
        </ul>
        <div class="cta cta-wrapper" style="transition: opacity 300ms ease 0s; transform: translate(103px, 0px); top: -48px; opacity: 1;">
            <a class="adsense-signin-link cta-signin" href="<?php echo SITE_URL . '/user/login'?>">
                Sign in</a> <a class="cta-signup" href="<?php echo SITE_URL . '/user/register'?>">
                Sign up</a>
        </div>
    </nav><button class="nav-toggle-button"><span class="icon-menu-els"><span class="menu-bar"></span> <span class="menu-bar"></span> <span class="menu-bar"></span></span></button>
</header>
<div class="main" role="main">
    <section class="section section-hero section-home-hero">
        <div class="site-width pos-relative">
            <div class="cols-row">
                <div class="section-hero-copy col-5 col-offset-7">
                    <h1>
                        Turn your passion into profit.
                    </h1>
                    <p class="font-large">
                        P.AdsSolution is a free, simple way to earn money by placing ads on your website.
                    </p>
                    <p>
                        <a class="button cta-main" href="<?php echo SITE_URL . '/user/register'?>">
                            Sign up Now</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
</div>
</body>
</html>