<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/jquery-1.12.2.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/mycustom.js"></script>
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/front-end.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/font-awesome.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/mycustom.css" rel="stylesheet">
    <?php
    echo $this->headTitle();
    echo $this->headLink();
    ?>
</head>
<body>
<div class="Wrapcontainer" id="page">
    <div class="wrap-header">
        <div class="container container_header">
            <a href="<?php echo SITE_URL . '/user/index' ?>" class="logo"><img style="width: 120px;height: 90px;" src="<?php echo STATIC_URL; ?>/images/peeredgelogotype.png" alt="eClick.vn" title="eClick.vn"></a>
            <div class="navigation">
                <div class="btn-toggle-nav">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
    </div>
    <div class="wrap-success">
        <?php echo $this->layout()->content; ?>
    </div>
</div>
<?php echo $this->headScript(); ?>
</body>
</html>