<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if lt IE 9]>
    <link href="/css/default/front-end.css" rel="stylesheet">
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/html5shiv.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/respond.min.js"></script>
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/jquery-1.11.1.min.js"></script>
    <![endif]-->
    <!--[if (gte IE 9) | (!IE)]><!-->
    <script type="text/javascript" src="<?php echo STATIC_URL; ?>/js/library/jquery-2.1.1.min.js"></script>
    <!--<![endif]-->
    <?php
    echo $this->headTitle();
    echo $this->headLink();
    ?>
</head>
<body>
<div id="page-backend" >
    <div id="top-navigation">
        <div class="navbar navbar-inverse" >
            <div class="navbar-header">
                <a class="navbar-brand" href="#"><img src="<?php echo STATIC_URL; ?>/images/logo-eclick.png" alt="logo"></a>
            </div>
        </div>
    </div>
    <div id="main-page" style="padding-left:0">
        <div class="container-fluid">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
<?php echo $this->headScript(); ?>
</body>
</html>